### DISCUSSION TITLE
Consider splitting action.yml Bash script into its own file

### DISCUSSION THREAD

**Discussion by jcbhmr** [spenserblack/actions-wiki#19] [Ideas]
If you're dead-set on maintaining Windows compatibility, I think this would require some testing to make sure that `#!/bin/bash` works to then `./my-script.sh` on a Windows system. I think it does, but I would still test it to be sure.

But realistically, most people are going to use `runs-on: ubuntu-latest` for just this specific action.

```yml
# This is probably what most people are going to use this action for...
on: push
jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: spenserblack/actions-wiki@vN
      # And that's literally it.
```

But hey, there might be a compelling reason that I'm missing!
