### ISSUE TITLE
Consider using an auto-tag release bot

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#12]
![image](https://user-images.githubusercontent.com/61068799/224775039-4b414d85-7f02-47bd-8dbd-7ec2c3822deb.png)

Currently tags seem to be aiming for a Docker-image like (that's the best analogy I can think of) tag system where for each version, there's like a major tag, a minor tag, and a patch tag.

So like v1.5.10 has:
- v1.5.10
- v1.5 => v1.5.10
- v1 => v1.5.10

And then when v1.5.11 comes out, it updates:
- v1 => v1.5.11
- v1.5 => v1.5.11
- v1.5.10 (stays pointing to pinned version)

And similarly, when v1.6.0 comes out:
- v1 => v1.6.0
- v1.5 => v1.5.11
- v1.6 => v1.6.0
- v1.6.0
- v1.5.11
- v1.5.10

At least I think that's what you're going for? It looks like the official GitHub actions use this technique: https://github.com/actions/checkout/tags

Here's a GitHub workflow action that might help automate this: https://github.com/actions/publish-action I know I know it's still in beta, but it is actively being used by GitHub's official actions (and others)! https://github.com/actions/publish-action/network/dependents And you can pin it to a specific commit if you don't want to get skewered by version bumps.

**Comment by jcbhmr** [comment]
Here's a live example code snippet: https://github.com/actions/setup-node/blob/10f562350248c03b1290d1d8a055102c0da3bebf/.github/workflows/release-new-action-version.yml#L25

```yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
