### ISSUE TITLE
Do you actually need a user-generated GitHub PAT?

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#5]
I notice from the readme:

> Unfortunately, ${{ github.token }} does not have access to updating wiki repositories, so it is necessary to create a new PAT.

I don't think this is true? I was under the impression from my own attempt at a sub-par wiki action https://github.com/jcbhmr/publish-to-github-wiki that you can just use the `${{ github.token }}` _as long as you have the `content: write` permission_.

```yml
name: Test publish to own wiki
on:
  push:
    paths:
      - index.sh
      - action.yml
      - .github/workflows/test-publish-to-own-wiki.yml
      - wiki/**
concurrency: test-publish-to-own-wiki
jobs:
  test-publish-to-own-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # This just uses the secrets.GITHUB_TOKEN (or github.token, both are equivalent)
      - uses: ./
```

Recently GitHub did change up their permissions defaults to make them **no longer write-permissive by default** which may have thrown things off? I have already been bitten by this: https://github.com/jcbhmr/devcontainer-features/issues/2

Am I completely wrong? Is there something I'm missing? 🤷‍♂️
