### ISSUE TITLE
Fix test script

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#58]
![image](https://user-images.githubusercontent.com/61068799/231872053-f91ad6da-d7bd-43c7-a61e-3340e2ab1f6b.png)

from #57 where i wanted to see it go green

doesn't work for forks

likely problem: idk
likely solution: some fiddling with the github token perms in the settings tab?

basically the token needs READONLY perms to just the "contents: read" flag _across forks_ which could be what's happening?

**Comment by spenserblack** [comment]
Screenshot is from a PR, right? IMO the solution is that this should be a dry-run for PRs, and actually push changes for pushes to `main`.

**Comment by jcbhmr** [comment]
> Screenshot is from a PR, right? IMO the solution is that this should be a dry-run for PRs, and actually push changes for pushes to `main`.

you're right. i was misunderstanding the error message. i thought it failed to _pull_ when (youre right) it failed to _push_

thus something is wrong with this?

```yml
      - uses: ./
        with:
          # For now, you'll need to manually specify a GitHub token until we
          # solve #2. The x: prefix is a dummy username.
          token: x:${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ github.ref == 'main' }}
```

**Comment by jcbhmr** [comment]
yeah confirmed: dry-run was FALSE for some reason:

![image](https://user-images.githubusercontent.com/61068799/232901073-03f0dc9d-41a2-482a-b1b1-c9e25d33218d.png)

https://github.com/spenserblack/actions-wiki/actions/runs/4693381558/jobs/8320289598?pr=57

**Comment by jcbhmr** [comment]
actually yeah that makes sense. pr has github.ref of `jcbhmr:some-branch` in:

```yml
dry-run: ${{ 'jcbhmr:some-branch' == main }}
dry-run: false
```

when it should be:

```yml
dry-run: ${{ github.ref != 'main' }}
dry-run: ${{ 'jcbhmr:some-branch' != 'main' }}
dry-run: true
```

🎉
