### ISSUE TITLE
Make GitHub token inputs/behaviour work like other ecosystem actions

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#59]
basically like this:

![image](https://user-images.githubusercontent.com/61068799/231873180-10407c85-6c45-4734-b8e6-01912a6da4d8.png)
https://github.com/actions/checkout

heck, we can even just _literally use the actions/checkout action_ since this is a _composite_ action to clone the .wiki.git folder into some /tmp/myfolder and then copy stuff over to it and then push _all without touching the github token_ (since it saves it in the remoteurl thing when it clones it, right?)

**Comment by jcbhmr** [comment]
i recommend closing #2 in favor of this since i have no idea what that issue was originally targetting. if you @spenserblack could fill me in thatd be great 😊

**Comment by spenserblack** [comment]
I'm not really sure what the suggested change is (besides using `actions/checkout` in this action). How would the behavior change?

> maybe close #2 in favor of this?

For #2, "support" isn't just code, but documentation. So a simple documentation change mentioning fine-grained tokens, and the differences (if any) between the two would resolve #2 for me.

**Comment by jcbhmr** [comment]
> I'm not really sure what the suggested change is (besides using `actions/checkout` in this action). How would the behavior change?

specifically:

```yml
- uses: spenserblack/actions-wiki@v1
  with:
    # No need for a token: ... setting
```

```yml
- uses: spenserblack/actions-wiki@v1
  with:
    # If you DO use a token: ... setting, it's without a username (no more x:gh_abc123...)
    token: ${{ secrets.GITHUB_TOKEN }}
```

```yml
- uses: spenserblack/actions-wiki@v1
  with:
    # If you use a custom PAT, you also don't need a username
    token: ${{ secrets.OCTOCAT_GITHUB_PAT }}
```
